FROM python:3.12-slim

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /app_support/static

ENV PYTHONPATH=/

WORKDIR /

CMD ["uvicorn", "app_support.main:app", "--host", "0.0.0.0", "--port", "8001"]