FROM python:3.12-slim

WORKDIR /bot

# Копируем только зависимости и код бота
COPY bot/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY bot ./bot

CMD ["python", "-m", "bot.main"]