services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - URL=http://app:8000

  app_support:
    build:
      context: .
      dockerfile: Dockerfile.app_support
    container_name: app_support
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - URL_SUPPORT=http://app_support:8001