[pytest]
testpaths = app/tests
asyncio_mode = auto
markers =
    positive: marks a test as a positive scenario (expected success)
    negative: marks a test as a negative scenario (expected failure or error)
    doesnt_work: marks the test as not working correctly
    positive1: marks a test as a positive scenario (expected success)
    negative1: marks a test as a negative scenario (expected failure or error)
