"""Added a table favorites

Revision ID: 33877f704d81
Revises: 597102a66038
Create Date: 2025-08-04 22:45:58.507544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33877f704d81'
down_revision: Union[str, None] = '597102a66038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_user_product_uc', 'favorites', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_product_uc', 'favorites', type_='unique')
    # ### end Alembic commands ###
