"""Update tables cart and orders

Revision ID: 4cca3ce4e4fb
Revises: 067df28efdec
Create Date: 2025-08-11 21:57:30.403907

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "4cca3ce4e4fb"
down_revision: str | None = "067df28efdec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
