"""Added a table favorites

Revision ID: 597102a66038
Revises: d6d9af08ead1
Create Date: 2025-08-04 22:22:58.078352

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "597102a66038"
down_revision: str | None = "d6d9af08ead1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
