"""cascade

Revision ID: 64f31971576c
Revises: a7c9b3bfc2ed
Create Date: 2026-03-16 22:11:52.772921

"""

from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "64f31971576c"
down_revision: str | None = "a7c9b3bfc2ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("cart_product_id_fkey"), "cart", type_="foreignkey")
    op.create_foreign_key(
        None, "cart", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        op.f("favorites_product_id_fkey"), "favorites", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "favorites", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("files_product_id_fkey"), "files", type_="foreignkey")
    op.create_foreign_key(
        None, "files", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("reviews_product_id_fkey"), "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "products", ["product_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(
        op.f("reviews_product_id_fkey"), "reviews", "products", ["product_id"], ["id"]
    )
    op.drop_constraint(None, "files", type_="foreignkey")
    op.create_foreign_key(
        op.f("files_product_id_fkey"), "files", "products", ["product_id"], ["id"]
    )
    op.drop_constraint(None, "favorites", type_="foreignkey")
    op.create_foreign_key(
        op.f("favorites_product_id_fkey"),
        "favorites",
        "products",
        ["product_id"],
        ["id"],
    )
    op.drop_constraint(None, "cart", type_="foreignkey")
    op.create_foreign_key(
        op.f("cart_product_id_fkey"), "cart", "products", ["product_id"], ["id"]
    )
    # ### end Alembic commands ###
