"""Added fields tg_username and tg_id in user table

Revision ID: 7916f92361fa
Revises: e7b005462543
Create Date: 2026-01-09 13:25:56.831928

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7916f92361fa"
down_revision: str | None = "e7b005462543"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("tg_id", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("tg_username", sa.String(), nullable=True))
    op.drop_constraint(op.f("users_telegram_key"), "users", type_="unique")
    op.create_unique_constraint(None, "users", ["tg_id"])
    op.drop_column("users", "telegram")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint(
        op.f("users_telegram_key"),
        "users",
        ["telegram"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("users", "tg_username")
    op.drop_column("users", "tg_id")
    # ### end Alembic commands ###
