"""add file_ids into products

Revision ID: a7c9b3bfc2ed
Revises: a1b2c3d4e5f6
Create Date: 2026-03-14 22:36:11.986766

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "a7c9b3bfc2ed"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
