"""changes have been made to the Chats table

Revision ID: b22ab0e5134d
Revises: eb7ec3aa93c5
Create Date: 2025-09-10 18:43:30.154192

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b22ab0e5134d"
down_revision: str | None = "eb7ec3aa93c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chats", "active", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chats", "active", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
