"""New tables chats and messages

Revision ID: bac4f367d83f
Revises: c097a19efcb4
Create Date: 2025-09-08 22:08:43.434189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac4f367d83f'
down_revision: Union[str, None] = 'c097a19efcb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'chats', 'users', ['employee_id'], ['id'])
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'users', ['chat_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.alter_column('chats', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
