"""Added fields telegram and is_verified in user table

Revision ID: e7b005462543
Revises: 26e244d1fee9
Create Date: 2026-01-08 18:32:11.236638

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e7b005462543"
down_revision: str | None = "26e244d1fee9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram", sa.String(), nullable=True))
    op.add_column("users", sa.Column("is_verified", sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, "users", ["telegram"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "is_verified")
    op.drop_column("users", "telegram")
    # ### end Alembic commands ###
