"""New tables chats and messages2

Revision ID: eb7ec3aa93c5
Revises: bac4f367d83f
Create Date: 2025-09-08 22:28:55.256144

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "eb7ec3aa93c5"
down_revision: str | None = "bac4f367d83f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
